language: android
jdk:
  - openjdk11
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-29
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - chmod +x ./gradlew
 

script: ./gradlew clean build

