language: android
jdk:
  - openjdk17

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/android-sdk

android:
  components:
    - tools
    - platform-tools
    - build-tools-34.0.0
    - android-34
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
before_install:
  #- gem install fir-cli
  - chmod +x gradlew
  #- mkdir "$ANDROID_HOME/licenses" || true
  - yes | sdkmanager --update
  #- yes | sdkmanager --licenses
  - yes | sdkmanager "platforms;android-34"

script: ./gradlew clean build
