language: android
jdk:
  - openjdk17

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
before_install:
  - chmod +x ./gradlew
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH


script: ./gradlew clean build
