language: android
jdk:
  - openjdk17

env:
  global:
    - ANDROID_SDK_ROOT=/usr/local/android-sdk

android:
  components:
    - tools
    - platform-tools
    - build-tools-34.0.0
    - android-34
    - extra-android-support
    - extra-google-google_play_services
    - extra-android-m2repository
    - extra-google-m2repository
    - addon-google_apis-google-21

before_install:
  - chmod +x ./gradlew
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - mkdir -p "$ANDROID_SDK_ROOT/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55\n" > "$ANDROID_SDK_ROOT/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n" > "$ANDROID_SDK_ROOT/licenses/android-sdk-preview-license"
  - sdkmanager "platforms;android-34" "build-tools;34.0.0"

script: ./gradlew clean build
