language: android
dist: xenial  # oder focal
jdk:
  - openjdk11

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.3
    - android-30
    - extra-android-m2repository
    - extra-google-m2repository

  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - sudo apt-get update && sudo apt-get install -y libxml2-dev libxslt1-dev
  - yes | sdkmanager "platforms;android-30"
  - yes | sdkmanager "build-tools;30.0.3"
  - yes | sdkmanager --licenses

script:
  - ./gradlew clean build
